### ISSUE TITLE
Mutes everything when Spotify is minimised to the tray

### ISSUE THREAD

**Issue by adigitoleo** [epicnyanpandi/SpotifyAdMuter#2]
In Spotify, there is an option to minimise the app to the tray when the close button is clicked. It is at Edit > Preferences > Startup and window behaviour and the option is called "Close button should minimize the Spotify window". This app seems to mute not only ads but also songs, i.e. everything, when that option is enabled and the close button is pressed. The icon is still visible in the system tray, and re-opening the window un-mutes the song.

Is there a way to make it work in minimized-to-tray mode as well?

**Comment by adigitoleo** [comment]
I encountered this on Spotify version `1.2.51.345.gcc39d911` installed with winget.

**Comment by enpandi** [comment]
After investigation, I don't think it is possible to make it work in minimized-to-tray mode using the current method.

Broadly speaking, the current method looks at the titles of the Spotify processes to determine whether there is a song playing. If there is a song playing, then one of the process names will be `[song name] - [artist name]`; otherwise it is something like `Spotify` or `Advertisement`. See [here](https://github.com/enpandi/SpotifyAdMuter/blob/64f5016fdb5a0a44d594d9807aa0e67f7a69807c/Context.cs#L132) for the logic.

I played around a bit with minimized-to-tray mode, but it appears that the minimized process information does not convey any information about whether a song or advertisement is playing -- all processes are titled `Spotify` regardless. I am not aware of another method to detect advertisements.

**Comment by adigitoleo** [comment]
I see. Thanks for investigating. Unfortunately I'm not aware of any solution either, short of messing around with proxy connections and blocking external hosts (which can be more destructive to app features and is probably not worth the trouble). I've recently found that Win + Ctrl + [Left|Right] switches desktops, so to remove Spotify from the current Alt-Tab menu I can just shift it to another desktop.

**Comment by enpandi** [comment]
Glad you were able to find a workaround :)
